CREATE DATABASE stackoverflowusers;
USE stackoverflowusers;
CREATE TABLE Users (
id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
username VARCHAR(45) NOT NULL,
email VARCHAR(45) NOT NULL,
password VARCHAR(45) NOT NULL
);